import { StyleSheet } from "react-native";
import { white } from "nativewind/dist/metro/picocolors";
import absoluteFillObject = StyleSheet.absoluteFillObject;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
  },
  wallpaper: {
    ...absoluteFillObject,
    flex: 1,
    resizeMode: "cover",
    alignItems: "center",
    alignContent: "center",
  },
  title: {
    color: "#fff",
    fontSize: 34,
    fontWeight: "400",
    textAlign: "center",
    textDecorationColor: "#000",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  subtitle: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "400",
    textAlign: "center",
    textDecorationColor: "#000",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  input: {
    backgroundColor: "rgba(255,255,255,0.2)",
    borderColor: "rgba(255,255,255,0.6)",
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 8,
    marginBottom: 16,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    width: "90%",
  },
  label: {
    width: "90%",
    alignSelf: "center",
    textAlign: "left",
    color: "#fff",
    fontSize: 14,
    marginBottom: 8,
  },

  button: {
    width: "90%",
    alignSelf: "center",
    backgroundColor: "rgba(255,255,255,0.2)",
    borderColor: "rgba(255,255,255,0.6)",
    borderWidth: 1,
    paddingVertical: 12,
    borderRadius: 8,
    shadowColor: "#000",
    shadowOpacity: 0.12,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  buttonDisabled: {
    opacity: 0.6,
  },
  buttonText: {
    color: "white",
    textAlign: "center",
    fontSize: 16,
    fontWeight: "400",
  },
  forgotText: {
    textAlign: "right",
    width: "90%",
    color: "white",
    marginVertical: 15,
  },
  footerText: {
    color: "white",
    marginTop: 8,
    textAlign: "center",
    textShadowOffset: { width: 0, height: 0 },
    textShadowColor: "#000",
    textShadowRadius: 2,
    fontSize: 14,
    marginVertical: 15,
  },
  footerLink: {
    textDecorationLine: "underline",
    fontWeight: "600",
    color: "#fff",
  },
  blurContainer: {
    paddingVertical: 20,
    paddingHorizontal: 25,
    width: "90%",
    margin: 16,
    textAlign: "center",
    justifyContent: "center",
    overflow: "hidden",
    borderRadius: 20,
    borderColor: "white",
    borderWidth: 0.5,
  },
});
